#!/bin/bash

#Dependencies: pacman-contrib 

UPDATES=$(checkupdates | wc -l ; checkupdates)
UPDATESWC=$(checkupdates | wc -l)

if [ "$UPDATESWC" == 0 ]; then
  notify-send "No Updates Available"
else
  notify-send "UPDATES : $UPDATES"
fi
