#!/bin/bash

ROFI="rofi -dmenu -i -p"
UPTIME=$(uptime -p)
WHO=$(whoami)

# Powermenu opts
declare -a opts=(
"Shutdown"
"Reboot"
"Suspend"
"Logout"
"Quit"
)

choice=$(printf '%s\n' "${opts[@]}" | ${ROFI} "$WHO | $UPTIME" "${@}")

main() {
case $choice in
    'Shutdown')
      if [[ "$(echo -e "No\nYes" | ${ROFI} 'Shutdown?')" == "Yes" ]]; then
                systemctl poweroff
            else
                echo "User chose not to Shutdown." && exit 0
            fi
            ;;

    'Reboot')
       if [[ "$(echo -e "No\nYes" | ${ROFI} 'Reboot?')" == "Yes" ]]; then
                systemctl reboot
            else
                echo "User chose not to Reboot." && exit 0
            fi
            ;;

    'Suspend')
      if [[ "$(echo -e "No\nYes" | ${ROFI} 'Suspend?')" == "Yes" ]]; then
                systemctl suspend
            else
                echo "User chose not to Suspend." && exit 0
            fi
            ;;

    'Logout')
      if [[ "$(echo -e "No\nYes" | ${ROFI} 'Logout?')" == "Yes" ]]; then
                 pkill -KILL -u "$USER"
            else
                echo "User chose not to Logout." && exit 1
            fi
            ;;

    'Quit')
        echo "Program terminated." && exit 0
        ;;
esac
}
main
