#!/bin/bash

# Variables
ROFI="rofi -dmenu -i -p"
WALLPAPER_DIR="${HOME}/Imagens/Wallpapers"
SET_BG="feh --bg-scale --no-fehbg --no-xinerama"

main() {
  choice="$(printf "Set\nRandom\nExit" | ${ROFI} "What would you like to do?")" 
  case $choice in
  "Set")
  wallpaper="$(sxiv -t -o "${WALLPAPER_DIR}")"
  ${SET_BG} "$wallpaper"
  notify-send "Wallpaper has been updated" -i $wallpaper
  ;;
  "Random")
  valid_paper="No"
  until [ "$valid_paper" = "Yes" ]; do
  pidof "feh" && killall "feh" 
  wallpaper="$(find "${WALLPAPER_DIR}" -type f | shuf -n 1)"
  ${SET_BG} "$wallpaper" &
  valid_paper="$(printf "Yes\nNo" | ${ROFI} "Do you like the new wallpaper?")"
done
  ;;
  "Exit") echo "Program terminated" && exit 1;;
esac
}

main
