#!/bin/bash

# TODO: Add a quit option in mount an umount functions

# Help message
help() {
     printf 'usb.sh [options]\n
    -h\tDisplays this help menu
    -m\tMount usb drive
    -u\tUmount usb drive\n'
}

# Mount Function
mount() {
  mountable="$(lsblk -lp | awk '/^\/dev\/sd.*part $/ { print $1 " ("$4")" }')"
  [ "$mountable" = "" ] && exit 1
  choice="$(printf '%s\n' "$mountable" | fzf --header="Mount options" || exit 1)"
  makedir="$(printf "$choice" | sed -e 's/(//' -e 's/)//' | awk -F '/' '{ print $3 }' | awk '{ print $1 }')"
  drive="$(printf "$choice" | awk '{ print $1 }')"
  mkdir -p "/tmp/usb-$makedir" && doas mount "$drive" "/tmp/usb-$makedir"
  printf "USB was mounted at /tmp/usb-$makedir"
}

# Umount Function
umount() {
  mount=$(lsblk -lp | grep "/tmp")
  [ "$mount" = "" ] && exit 1
  umount_choice="$(printf '%s\n' "$mount" | awk '{ print $1 }' | fzf --header="Umount options" || exit 1)"
  doas umount "$umount_choice"
}

# Environment Variables
while getopts "hmu" arg 2>/dev/null; do
    case "${arg}" in
        h) help ;;
        m) mount ;;
        u) umount ;;
        *) help
    esac
done
